### PR TITLE
Fixes leak and Socket.disconnect() not calling onClose

### LINKED ISSUE #110: Socket "leak"
While looking at #109, discovered that the `Socket` class "leaks" because a [Timer holds onto a strong reference to it](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Socket.swift#L415-L418), even after calling [`disconnect()`](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Socket.swift#L182-L187).

As far as I can tell, it looks like [`disconnect()` may not call `onClose` either](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Socket.swift#L179), because the underlying web socket's `delegate` gets set to `nil`

Was thinking of opening a PR that calls `self.onConnectionClosed()` in the `disconnect()` method.   I believe this will fix both of the above issues.  @davidstump Thoughts?

Not sure if that will cause issues with with auto reconnect though (https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Socket.swift#L360)

### PR DESCRIPTION
**Pull request by darrenclark**
Fixes #110, specifically:

- `Socket` may "leak" even after disconnected, because [a `Timer` holds a strong reference to it](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Socket.swift#L415-L418), even after `disconnect()` is called
- I don't believe [`onClose` was being fired](https://github.com/davidstump/SwiftPhoenixClient/blob/b2e7b69607d5fd6f8a7ec05f063f78012ba9551a/Sources/Socket.swift#L179) because the `connection.delegate` gets set to `nil`

I'm not 100% sure calling `onConnectionClosed()` is the right option here though, as there may be unintended side effects (like the autoreconnect timer starting)  @davidstump thoughts?

### CODE REVIEW

File: Sources/Socket.swift [hunk 1]
```diff
@@ -182,6 +182,8 @@ public class Socket {
     public func disconnect(_ callback: (() -> Void)? = nil) {
         connection.delegate = nil
         connection.disconnect()
+
+        onConnectionClosed()
```
Comment (dsrees) [inline Sources/Socket.swift]: This will have unintended side effects such as triggering an error and potentially attempting a reconnect. The `onConnectionClosed()` method is built to be called when the connection is disconnected from a call to the `WebSocketDelegate`

I think the best thing to do here is to only perform the required calls
```
self.heartbeatTimer?.invalidate()
self.onCloseCallbacks.forEach( { $0() } )
```

Comment (darrenclark) [reply Sources/Socket.swift]: Okay, cool, will make those fixes!

**Comment by darrenclark** [comment]
@dsrees Thanks for taking the time to review this!

I've made the changes & added a test for this.
