### PR TITLE
Strong memory cycle fixes

### LINKED ISSUE #109: Leaked Channels
My application joins and leaves different channels depending on where the user is in the application.

During some profiling tests I noticed some leaked objects, that appeared to be generated following calls to channel.leave(). Originally I assumed it was my code but in the end I managed to find the following in the memory debugger which seems to indicate an orphaned channel, several closure contexts, and cyclic references to PhxTimer and Push. Essentially the channel is never deallocated and however many channels the application joins they always persist in memory.

memory_graph

I have managed to solve the issue with the following changes https://github.com/Lankester/SwiftPhoenixClient/commit/0c5c263776238bf0af8c9cc1e20937e739294eab but despite the tests passing I am not sure it is the best way.

If it turns out to be a reasonable solution, I'd be happy to submit a PR.

### PR DESCRIPTION
**Pull request by darrenclark**
Fixes #109

Fixes strong reference cycles by using `weak`, following these "rules":

- `Socket` owns `Channel`s (with `Channel` having a weak reference back to `Socket`)
- `Channel` owns `Push`es  (with `Push` having a weak reference back to `Channel`)
- `Socket` / `Channel` own `PhxTimer`s, used `weak` in callback blocks to break the strong reference cycle
    - In addition, `Socket` / `Channel` now also `reset()` their timers in `deinit`

### CODE REVIEW

File: Tests/ChannelSpec.swift [hunk 1]
```diff
@@ -53,11 +53,16 @@ class ChannelSpec: QuickSpec {
...
                 let joinPush = channel.joinPush
-                expect(joinPush?.channel.topic).to(equal(channel.topic))
+                expect(joinPush?.channel?.topic).to(equal(channel.topic))
                 expect(joinPush?.payload["one"] as? Int).to(equal(2))
                 expect(joinPush?.event).to(equal(ChannelEvent.join))
                 expect(joinPush?.timeout).to(equal(PHOENIX_DEFAULT_TIMEOUT))
             })
+
+            it("should not introduce any retain cycles", closure: {
+                weak var channel = Channel(topic: "topic", params: ["one": 2], socket: mockSocket)
```
Comment (dsrees) [inline Tests/ChannelSpec.swift]: 👍 thank you for not only fixing the issue but also providing test cases with it
